---
title: "Checking Missingness"
author: "Spiro Stilianoudakis"
date: "September 25, 2017"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(openxlsx)
library(scales)
library(caret)
library(knitr)
```

```{r include=FALSE}

setwd("Z:/Shares/Biostatistics/Projects/BCL/Research Projects/Open/BCL - 2017 - R96 (Sharifzadeh - Internal Medicine)/1 - Data")
list.files()
med_hist <- read.xlsx("Jh QoL all 7-19-17 FINAL cleaned DEID.xlsx",
                    sheet = 1,
                    startRow = 1,
                    colNames = TRUE,
                    na.strings = c("","n/a","N/a"),
                    detectDates = TRUE)
quest <- read.xlsx("NeuroQoL_FINAL_YS_DEID.xlsx",
                           sheet = 1,
                           startRow = 1,
                           colNames = TRUE)


#Removing rows where timing of the survey was after 3 months

colnames(quest)[3] <- "timing_of_survey"

quest2 <- quest[quest[,3] <= 3,]
dim(quest2)

#Removing all but the QoL column, the 4 uncertainty related questions, the timing, and location

quest3 <- quest2[,which(colnames(quest2)=="Data.Base.ID" |
                                          colnames(quest2)=="timing_of_survey" |
                                          colnames(quest2)=="Location.(0.office,.1.home)" |
                                          colnames(quest2)=="Overall.quality.of.life" |
                                          colnames(quest2)=="Feel.uncertain.about.future?" |
                                          colnames(quest2)=="Setbacks.in.condition?" |
                                          colnames(quest2)=="Concerned.about.disrupting.family.life?" |
                                          colnames(quest2)=="Outlook.on.future.worsen?")]
dim(quest3)
names(quest3) <- c("ID", "timing_of_survey", "location_of_survey", "QoL", "uncertainty1", "uncertainty2", "uncertainty3","uncertainty4")

#Removing rows with either 999 or NA in them or others

quest4 <- quest3[complete.cases(quest3), ]
quest5 <- subset(quest4, !quest4$ID %in% quest4$ID[quest4$QoL==999 |
                                                                   quest4$uncertainty1==999 |
                                                                   quest4$uncertainty2==999 |
                                                                   quest4$uncertainty3==999 |
                                                                   quest4$uncertainty4==999])
num <- c("1","2","3","4")
grep(paste(num, collapse = "|"), quest5$uncertainty2,invert = TRUE)
quest5 <- quest5[-grep(paste(num, collapse = "|"), quest5$uncertainty2,invert = TRUE),]
dim(quest5)
head(quest5)
str(quest5)

quest5$uncertainty2 <- as.numeric(quest5$uncertainty2)

#Transforming QoL 

QoL_calc <- function(x){
  ((x-1)/(max(quest5$QoL)-min(quest5$QoL)))*100
}
quest5$QoL_score <- QoL_calc(quest5$QoL)

#Adding scores for uncertainty

quest5$raw_score <- rowMeans(quest5[,5:8])

#Transforming uncertainty

uncertain_calc <- function(x){
  ((x-1)/(max(quest5$uncertainty1)-min(quest5$uncertainty1)))*100
}
quest5$uncertain_score <- uncertain_calc(quest5$raw_score)

#removing QoL, uncertainty1-4
quest6 <- quest5[,c(1,2,3,9,11)]


#Determining which patients (IDs) have resposes for t=1 or 3 but no baseline
t3vt1 <- setdiff(quest6$ID[which(quest6$timing_of_survey==3)],quest6$ID[which(quest6$timing_of_survey==1)])
t3vbase <- setdiff(quest6$ID[which(quest6$timing_of_survey==3)],quest6$ID[which(quest6$timing_of_survey==0)])
t1vbase <- setdiff(quest6$ID[which(quest6$timing_of_survey==1)],quest6$ID[which(quest6$timing_of_survey==0)])
union(union(t3vt1,t3vbase),t1vbase)

#Removing patients that have response for t1 or t3 but not baseline
quest7 <- quest6[-which(quest6$ID %in% union(union(t3vt1,t3vbase),t1vbase)),]

#Seperating by timing of survey
baseline <- subset(quest7,quest7$timing_of_survey==0)
t1 <- subset(quest7,quest7$timing_of_survey==1)
t3 <- subset(quest7,quest7$timing_of_survey==3)

#Adding covariates from med_hist data to the questionaiire data
vars <- c(1,4,7,10,13,17,19,21,9,18,26,32)
med_hist2 <- med_hist[,vars]
names(med_hist2) <- c("ID", "Gender", "Age_Group", "prior_brain_radiation", "radiation_type",
                      "prior_resection", "tumor_histology", "histology", "KPS", 
                      "concurrent_chemo", "tumor_location", "cancer_still_affecting" )

#which patients have a baseline,t1,t3 response but do not appear in medical history data
setdiff(baseline$ID, med_hist2$ID)
setdiff(t1$ID, med_hist2$ID)
setdiff(t3$ID, med_hist2$ID)

#remove these from questionaire data
baseline <- baseline[-which(baseline$ID==69 | baseline$ID==149),]
t1 <- t1[-which(t1$ID==69),]

#check that all baseline responders are in medical data
setdiff(baseline$ID, med_hist2$ID)
setdiff(t1$ID, med_hist2$ID)
setdiff(t1$ID, med_hist2$ID)

#removing patients (IDs) from medical history data that do not appear in the final questionaire data

med_hist3 <- med_hist2[which(med_hist2$ID %in% baseline$ID),]
all.equal(med_hist3$ID,baseline$ID)

#fixing the variable classes
med_hist3$Gender <- ifelse(med_hist3$Gender==1,0,1)
med_hist3$Gender <- factor(med_hist3$Gender)

med_hist3$Age_Group <- ifelse(med_hist3$Age_Group==1,0,1)
med_hist3$Age_Group <- factor(med_hist3$Age_Group)

med_hist3$prior_brain_radiation <- ifelse(grepl("o",med_hist3$prior_brain_radiation),0,1)
med_hist3$prior_brain_radiation <- factor(med_hist3$prior_brain_radiation)

table(med_hist3$radiation_type)
which(med_hist3$radiation_type==4)
med_hist3$radiation_type[which(med_hist3$radiation_type==4)] <- 2
table(med_hist3$radiation_type)
med_hist3$radiation_type <- factor(med_hist3$radiation_type)

med_hist3$prior_resection <- ifelse(grepl("o",med_hist3$prior_resection),0,1)
med_hist3$prior_resection <- factor(med_hist3$prior_resection)

med_hist3$histology <- ifelse(med_hist3$histology==5,0,1)
med_hist3$histology <- factor(med_hist3$histology)

med_hist3$concurrent_chemo <- ifelse(grepl("o",med_hist3$concurrent_chemo),0,1)
med_hist3$concurrent_chemo <- factor(med_hist3$concurrent_chemo)

med_hist3$cancer_still_affecting <- ifelse(grepl("o",med_hist3$cancer_still_affecting),0,1)
med_hist3$cancer_still_affecting <- factor(med_hist3$cancer_still_affecting)

#dropping tumor_histology and tumor_location because there are too many subgroups
names(med_hist3)
med_hist4 <- med_hist3[,-c(7,11)]

str(med_hist4)

#Adding medical history to each subset of the questionaire data

base_med <- merge(baseline,med_hist4)
t1_med <- merge(t1,med_hist4)
t3_med <- merge(t3,med_hist4)

#seeing if any of the data have missing values
which(rowSums(is.na(base_med))!=0)
which(rowSums(is.na(t1_med))!=0)
which(rowSums(is.na(t3_med))!=0)

#remove missing values from base_med data
base_med <- base_med[-which(rowSums(is.na(base_med))!=0),]

```



```{r echo=FALSE}

Variable <- c("Baseline",
              "t = 1",
              "t = 3")

x <- c(dim(base_med)[1],dim(t1_med)[1],dim(t3_med)[1])  

y <- c(mean(base_med$QoL_score[which(base_med$Age_Group==0)]),mean(t1_med$QoL_score[which(t1_med$Age_Group==0)]),mean(t3_med$QoL_score[which(t3_med$Age_Group==0)]))
z <- c(mean(base_med$QoL_score[which(base_med$Age_Group==1)]),mean(t1_med$QoL_score[which(t1_med$Age_Group==1)]),mean(t3_med$QoL_score[which(t3_med$Age_Group==1)]))

y2 <- c(mean(base_med$QoL_score[which(base_med$Gender==0)]),mean(t1_med$QoL_score[which(t1_med$Gender==0)]),mean(t3_med$QoL_score[which(t3_med$Gender==0)]))
z2 <- c(mean(base_med$QoL_score[which(base_med$Gender==1)]),mean(t1_med$QoL_score[which(t1_med$Gender==1)]),mean(t3_med$QoL_score[which(t3_med$Gender==1)]))

y3 <- c(mean(base_med$QoL_score[which(base_med$prior_brain_radiation==0)]),mean(t1_med$QoL_score[which(t1_med$prior_brain_radiation==0)]),mean(t3_med$QoL_score[which(t3_med$prior_brain_radiation==0)]))
z3 <- c(mean(base_med$QoL_score[which(base_med$prior_brain_radiation==1)]),mean(t1_med$QoL_score[which(t1_med$prior_brain_radiation==1)]),mean(t3_med$QoL_score[which(t3_med$prior_brain_radiation==1)]))

y4 <- c(mean(base_med$QoL_score[which(base_med$radiation_type==1)]),mean(t1_med$QoL_score[which(t1_med$radiation_type==1)]),mean(t3_med$QoL_score[which(t3_med$radiation_type==1)]))
z4 <- c(mean(base_med$QoL_score[which(base_med$radiation_type==2)]),mean(t1_med$QoL_score[which(t1_med$radiation_type==2)]),mean(t3_med$QoL_score[which(t3_med$radiation_type==2)]))
w4 <- c(mean(base_med$QoL_score[which(base_med$radiation_type==3)]),mean(t1_med$QoL_score[which(t1_med$radiation_type==3)]),mean(t3_med$QoL_score[which(t3_med$radiation_type==3)]))
v4 <- c(mean(base_med$QoL_score[which(base_med$radiation_type==5)]),mean(t1_med$QoL_score[which(t1_med$radiation_type==5)]),0) #mean(t3_med$QoL_score[which(t3_med$radiation_type==5)])) there are none in this category

y5 <- c(mean(base_med$QoL_score[which(base_med$prior_resection==0)]),mean(t1_med$QoL_score[which(t1_med$prior_resection==0)]),mean(t3_med$QoL_score[which(t3_med$prior_resection==0)]))
z5 <- c(mean(base_med$QoL_score[which(base_med$prior_resection==1)]),mean(t1_med$QoL_score[which(t1_med$prior_resection==1)]),mean(t3_med$QoL_score[which(t3_med$prior_resection==1)]))

#y6 <- c(mean(base_med$QoL_score[which(base_med$histology==0)]),mean(t1_med$QoL_score[which(t1_med$histology==0)]),mean(t3_med$QoL_score[which(t3_med$histology==0)]))
#z6 <- c(mean(base_med$QoL_score[which(base_med$histology==1)]),mean(t1_med$QoL_score[which(t1_med$histology==1)]),mean(t3_med$QoL_score[which(t3_med$histology==1)]))

y7 <- c(mean(base_med$KPS),mean(t1_med$KPS),mean(t3_med$KPS))

#y8 <- c(mean(base_med$QoL_score[which(base_med$concurrent_chemo==0)]),mean(t1_med$QoL_score[which(t1_med$concurrent_chemo==0)]),mean(t3_med$QoL_score[which(t3_med$concurrent_chemo==0)]))
#z8 <- c(mean(base_med$QoL_score[which(base_med$concurrent_chemo==1)]),mean(t1_med$QoL_score[which(t1_med$concurrent_chemo==1)]),mean(t3_med$QoL_score[which(t3_med$concurrent_chemo==1)]))

#y9 <- c(mean(base_med$QoL_score[which(base_med$cancer_still_affecting==0)]),mean(t1_med$QoL_score[which(t1_med$cancer_still_affecting==0)]),mean(t3_med$QoL_score[which(t3_med$cancer_still_affecting==0)]))
#z9 <- c(mean(base_med$QoL_score[which(base_med$cancer_still_affecting==1)]),mean(t1_med$QoL_score[which(t1_med$cancer_still_affecting==1)]),mean(t3_med$QoL_score[which(t3_med$cancer_still_affecting==1)]))

comparisons <- cbind.data.frame(Variable,x,
                          y, z,
                          y2, z2,
                          y3, z3,
                          y4,z4,w4,v4,
                          y5, z5,
                          y7)

compare <- cbind(comparisons[,1],round(comparisons[,-1], 1))
names(compare) <- c("Timing","Total", "Age<60","Age>=60","Male","Female",
                    "No Prior Rad","Prior Rad","Rad type 1",
                    "Rad type 2","Rad type 3","Rad type 5",
                    "No prior resection","Prior resection",
                    "KPS")

#comparisons
kable(compare, caption="Mean QoL across the different levels of covariates of interest.")
#knitr::kable(comparisons, format = "html")

```




```{r echo=FALSE}
Variable <- c("Baseline",
              "t = 1",
              "t = 3")

x <- c(dim(base_med)[1],dim(t1_med)[1],dim(t3_med)[1])  

y <- c(mean(base_med$uncertain_score[which(base_med$Age_Group==0)]),mean(t1_med$uncertain_score[which(t1_med$Age_Group==0)]),mean(t3_med$uncertain_score[which(t3_med$Age_Group==0)]))
z <- c(mean(base_med$uncertain_score[which(base_med$Age_Group==1)]),mean(t1_med$uncertain_score[which(t1_med$Age_Group==1)]),mean(t3_med$uncertain_score[which(t3_med$Age_Group==1)]))

y2 <- c(mean(base_med$uncertain_score[which(base_med$Gender==0)]),mean(t1_med$uncertain_score[which(t1_med$Gender==0)]),mean(t3_med$uncertain_score[which(t3_med$Gender==0)]))
z2 <- c(mean(base_med$uncertain_score[which(base_med$Gender==1)]),mean(t1_med$uncertain_score[which(t1_med$Gender==1)]),mean(t3_med$uncertain_score[which(t3_med$Gender==1)]))

y3 <- c(mean(base_med$uncertain_score[which(base_med$prior_brain_radiation==0)]),mean(t1_med$uncertain_score[which(t1_med$prior_brain_radiation==0)]),mean(t3_med$uncertain_score[which(t3_med$prior_brain_radiation==0)]))
z3 <- c(mean(base_med$uncertain_score[which(base_med$prior_brain_radiation==1)]),mean(t1_med$uncertain_score[which(t1_med$prior_brain_radiation==1)]),mean(t3_med$uncertain_score[which(t3_med$prior_brain_radiation==1)]))

y4 <- c(mean(base_med$uncertain_score[which(base_med$radiation_type==1)]),mean(t1_med$uncertain_score[which(t1_med$radiation_type==1)]),mean(t3_med$uncertain_score[which(t3_med$radiation_type==1)]))
z4 <- c(mean(base_med$uncertain_score[which(base_med$radiation_type==2)]),mean(t1_med$uncertain_score[which(t1_med$radiation_type==2)]),mean(t3_med$uncertain_score[which(t3_med$radiation_type==2)]))
w4 <- c(mean(base_med$uncertain_score[which(base_med$radiation_type==3)]),mean(t1_med$uncertain_score[which(t1_med$radiation_type==3)]),mean(t3_med$uncertain_score[which(t3_med$radiation_type==3)]))
v4 <- c(mean(base_med$uncertain_score[which(base_med$radiation_type==5)]),mean(t1_med$uncertain_score[which(t1_med$radiation_type==5)]),0) #mean(t3_med$uncertain_score[which(t3_med$radiation_type==5)])) there are none in this category

y5 <- c(mean(base_med$uncertain_score[which(base_med$prior_resection==0)]),mean(t1_med$uncertain_score[which(t1_med$prior_resection==0)]),mean(t3_med$uncertain_score[which(t3_med$prior_resection==0)]))
z5 <- c(mean(base_med$uncertain_score[which(base_med$prior_resection==1)]),mean(t1_med$uncertain_score[which(t1_med$prior_resection==1)]),mean(t3_med$uncertain_score[which(t3_med$prior_resection==1)]))

#y6 <- c(mean(base_med$uncertain_score[which(base_med$histology==0)]),mean(t1_med$uncertain_score[which(t1_med$histology==0)]),mean(t3_med$uncertain_score[which(t3_med$histology==0)]))
#z6 <- c(mean(base_med$uncertain_score[which(base_med$histology==1)]),mean(t1_med$uncertain_score[which(t1_med$histology==1)]),mean(t3_med$uncertain_score[which(t3_med$histology==1)]))

y7 <- c(mean(base_med$KPS),mean(t1_med$KPS),mean(t3_med$KPS))

#y8 <- c(mean(base_med$uncertain_score[which(base_med$concurrent_chemo==0)]),mean(t1_med$uncertain_score[which(t1_med$concurrent_chemo==0)]),mean(t3_med$uncertain_score[which(t3_med$concurrent_chemo==0)]))
#z8 <- c(mean(base_med$uncertain_score[which(base_med$concurrent_chemo==1)]),mean(t1_med$uncertain_score[which(t1_med$concurrent_chemo==1)]),mean(t3_med$uncertain_score[which(t3_med$concurrent_chemo==1)]))

#y9 <- c(mean(base_med$uncertain_score[which(base_med$cancer_still_affecting==0)]),mean(t1_med$uncertain_score[which(t1_med$cancer_still_affecting==0)]),mean(t3_med$uncertain_score[which(t3_med$cancer_still_affecting==0)]))
#z9 <- c(mean(base_med$uncertain_score[which(base_med$cancer_still_affecting==1)]),mean(t1_med$uncertain_score[which(t1_med$cancer_still_affecting==1)]),mean(t3_med$uncertain_score[which(t3_med$cancer_still_affecting==1)]))

comparisons <- cbind.data.frame(Variable,x,
                          y, z,
                          y2, z2,
                          y3, z3,
                          y4,z4,w4,v4,
                          y5, z5,
                          y7)

compare <- cbind(comparisons[,1],round(comparisons[,-1], 1))
names(compare) <- c("Timing","Total", "Age<60","Age>=60","Male","Female",
                    "No Prior Rad","Prior Rad","Rad type 1",
                    "Rad type 2","Rad type 3","Rad type 5",
                    "No prior resection","Prior resection",
                    "KPS")

#comparisons
kable(compare, caption="Mean Uncertainty score across the different levels of covariates of interest.")
#knitr::kable(comparisons, format = "html")
```

```{r include=FALSE}

#Plotting QoL over time
#Consider all patients that had measurments at baseline, t1, and t3
intersect(intersect(base_med$ID,t1_med$ID),t3_med$ID)
ids <- intersect(intersect(base_med$ID,t1_med$ID),t3_med$ID)
which(base_med$ID %in% ids)

mean_all_base <- mean(base_med$QoL_score[which(base_med$ID %in% ids)])
t.test(base_med$QoL_score[which(base_med$ID %in% ids)])$conf.int[1:2]

mean_all_t1 <- mean(t1_med$QoL_score[which(t1_med$ID %in% ids)])
t.test(t1_med$QoL_score[which(t1_med$ID %in% ids)])$conf.int[1:2]

mean_all_t3 <- mean(t3_med$QoL_score[which(t3_med$ID %in% ids)])
t.test(t3_med$QoL_score[which(t3_med$ID %in% ids)])$conf.int[1:2]

#consider all patients that had measurements at baseline and t1
setdiff(intersect(base_med$ID,t1_med$ID),t3_med$ID)
ids <- setdiff(intersect(base_med$ID,t1_med$ID),t3_med$ID)
which(base_med$ID %in% ids)

mean_2_base <- mean(base_med$QoL_score[which(base_med$ID %in% ids)])
t.test(base_med$QoL_score[which(base_med$ID %in% ids)])$conf.int[1:2]

mean_2_t1 <- mean(t1_med$QoL_score[which(t1_med$ID %in% ids)])
t.test(t1_med$QoL_score[which(t1_med$ID %in% ids)])$conf.int[1:2]

#consider all patients that only had measurement at baseline
setdiff(setdiff(base_med$ID,t1$ID),t3_med$ID)
ids <- setdiff(setdiff(base_med$ID,t1$ID),t3_med$ID)
which(base_med$ID %in% ids)

mean_1_base <- mean(base_med$QoL_score[which(base_med$ID %in% ids)])
t.test(base_med$QoL_score[which(base_med$ID %in% ids)])$conf.int[1:2]

```

```{r echo=FALSE}
#Ploting the mean QOL across time

plot(x=c(0,1,3),y=c(mean_all_base,mean_all_t1,mean_all_t3),
     ylim=c(55,70),type = "b",lty=1,pch=2,
     xlab="Timing (months)",ylab="QoL Score",
     main="Mean QoL by Dropout Time")
lines(x=c(0,1),y=c(mean_2_base,mean_2_t1),ylim=c(55,70),type = "b", lty=2)
points(x=0,y=mean_1_base,pch=5)
legend("bottomright",c("Complete","Dropout at 3 months","Dropout at 1 month"),lty=c(1,2,0),pch=c(2,1,5))


```

```{r include=FALSE}
#Plotting Uncertainty over time
#Consider all patients that had measurments at baseline, t1, and t3
intersect(intersect(base_med$ID,t1_med$ID),t3_med$ID)
ids <- intersect(intersect(base_med$ID,t1_med$ID),t3_med$ID)
which(base_med$ID %in% ids)

mean_all_base <- mean(base_med$uncertain_score[which(base_med$ID %in% ids)])
t.test(base_med$uncertain_score[which(base_med$ID %in% ids)])$conf.int[1:2]

mean_all_t1 <- mean(t1_med$uncertain_score[which(t1_med$ID %in% ids)])
t.test(t1_med$uncertain_score[which(t1_med$ID %in% ids)])$conf.int[1:2]

mean_all_t3 <- mean(t3_med$uncertain_score[which(t3_med$ID %in% ids)])
t.test(t3_med$uncertain_score[which(t3_med$ID %in% ids)])$conf.int[1:2]

#consider all patients that had measurements at baseline and t1
setdiff(intersect(base_med$ID,t1_med$ID),t3_med$ID)
ids <- setdiff(intersect(base_med$ID,t1_med$ID),t3_med$ID)
which(base_med$ID %in% ids)

mean_2_base <- mean(base_med$uncertain_score[which(base_med$ID %in% ids)])
t.test(base_med$uncertain_score[which(base_med$ID %in% ids)])$conf.int[1:2]

mean_2_t1 <- mean(t1_med$uncertain_score[which(t1_med$ID %in% ids)])
t.test(t1_med$uncertain_score[which(t1_med$ID %in% ids)])$conf.int[1:2]

#consider all patients that only had measurement at baseline
setdiff(setdiff(base_med$ID,t1$ID),t3_med$ID)
ids <- setdiff(setdiff(base_med$ID,t1$ID),t3_med$ID)
which(base_med$ID %in% ids)

mean_1_base <- mean(base_med$uncertain_score[which(base_med$ID %in% ids)])
t.test(base_med$uncertain_score[which(base_med$ID %in% ids)])$conf.int[1:2]
```

```{r echo=FALSE}
#Ploting the mean QOL across time
plot(x=c(0,1,3),y=c(mean_all_base,mean_all_t1,mean_all_t3),
     ylim=c(20,45),type = "b",lty=1,pch=2,
     xlab="Timing (months)",ylab="Uncertainty Score",
     main="Mean Uncertainty by Dropout Time")
lines(x=c(0,1),y=c(mean_2_base,mean_2_t1),ylim=c(20,45),type = "b", lty=2)
points(x=0,y=mean_1_base,pch=5)
legend("topright",c("Complete","Dropout at 3 months","Dropout at 1 month"),lty=c(1,2,0),pch=c(2,1,5))

```

