---
title: "Checking Missingness 2"
author: "Spiro"
date: "September 27, 2017"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(openxlsx)
library(scales)
library(caret)
library(knitr)
```

```{r echo=FALSE}
setwd("Z:/Shares/Biostatistics/Projects/BCL/Research Projects/Open/BCL - 2017 - R96 (Sharifzadeh - Internal Medicine)/1 - Data")
#setwd("T:/Biostatistics/Projects/BCL/Research Projects/Open/BCL - 2017 - R96 (Sharifzadeh - Internal Medicine)/1 - Data")

med_hist <- read.xlsx("Jh QoL all 7-19-17 FINAL cleaned DEID.xlsx",
                    sheet = 1,
                    startRow = 1,
                    colNames = TRUE,
                    na.strings = c("","n/a","N/a"),
                    detectDates = TRUE)
quest <- read.xlsx("NeuroQoL_FINAL_YS_DEID.xlsx",
                           sheet = 1,
                           startRow = 1,
                           colNames = TRUE)
attach(med_hist)
attach(quest)
```


```{r include=FALSE}
#Removing rows where timing of the survey was after 3 months

colnames(quest)[3] <- "timing_of_survey"

quest2 <- quest[quest[,3] <= 3,]
dim(quest2)

#Removing all but the QoL column, the 4 uncertainty related questions, the timing, and location

quest3 <- quest2[,which(colnames(quest2)=="Data.Base.ID" |
                                          colnames(quest2)=="timing_of_survey" |
                                          colnames(quest2)=="Location.(0.office,.1.home)" |
                                          colnames(quest2)=="Overall.quality.of.life" |
                                          colnames(quest2)=="Feel.uncertain.about.future?" |
                                          colnames(quest2)=="Setbacks.in.condition?" |
                                          colnames(quest2)=="Concerned.about.disrupting.family.life?" |
                                          colnames(quest2)=="Outlook.on.future.worsen?")]
dim(quest3)
names(quest3) <- c("ID", "timing_of_survey", "location_of_survey", "QoL", "uncertainty1", "uncertainty2", "uncertainty3","uncertainty4")

#Removing rows with either 999 or NA in them or others

quest4 <- quest3[complete.cases(quest3), ]
quest5 <- subset(quest4, !quest4$ID %in% quest4$ID[quest4$QoL==999 |
                                                                   quest4$uncertainty1==999 |
                                                                   quest4$uncertainty2==999 |
                                                                   quest4$uncertainty3==999 |
                                                                   quest4$uncertainty4==999])
num <- c("1","2","3","4")
grep(paste(num, collapse = "|"), quest5$uncertainty2,invert = TRUE)
quest5 <- quest5[-grep(paste(num, collapse = "|"), quest5$uncertainty2,invert = TRUE),]
dim(quest5)
head(quest5)
str(quest5)

quest5$uncertainty2 <- as.numeric(quest5$uncertainty2)

#Transforming QoL 

QoL_calc <- function(x){
  ((x-1)/(max(quest5$QoL)-min(quest5$QoL)))*100
}
quest5$QoL_score <- QoL_calc(quest5$QoL)

#Adding scores for uncertainty

quest5$raw_score <- rowMeans(quest5[,5:8])

#Transforming uncertainty

uncertain_calc <- function(x){
  ((x-1)/(max(quest5$uncertainty1)-min(quest5$uncertainty1)))*100
}
quest5$uncertain_score <- uncertain_calc(quest5$raw_score)

#removing QoL, uncertainty1-4
quest6 <- quest5[,c(1,2,3,9,11)]


#Determining which patients (IDs) have resposes for t=1 or 3 but no baseline
#t3vt1 <- setdiff(quest6$ID[which(quest6$timing_of_survey==3)],quest6$ID[which(quest6$timing_of_survey==1)])
#t3vbase <- setdiff(quest6$ID[which(quest6$timing_of_survey==3)],quest6$ID[which(quest6$timing_of_survey==0)])
#t1vbase <- setdiff(quest6$ID[which(quest6$timing_of_survey==1)],quest6$ID[which(quest6$timing_of_survey==0)])
#union(union(t3vt1,t3vbase),t1vbase)

quest7 <- quest6

#Removing patients that have response for t1 or t3 but not baseline
#quest7 <- quest6[-which(quest6$ID %in% union(union(t3vt1,t3vbase),t1vbase)),]

#Seperating by timing of survey
baseline <- subset(quest7,quest7$timing_of_survey==0)
t1 <- subset(quest7,quest7$timing_of_survey==1)
t3 <- subset(quest7,quest7$timing_of_survey==3)

#Adding covariates from med_hist data to the questionaiire data
vars <- c(1,4,6,7,10,13,17,19,21,9,18,26,32)
med_hist2 <- med_hist[,vars]
names(med_hist2) <- c("ID", "Gender", "Age_cont", "Age_Group", "prior_brain_radiation", "radiation_type",
                      "prior_resection", "tumor_histology", "histology", "KPS", 
                      "concurrent_chemo", "tumor_location", "cancer_still_affecting" )

#which patients have a baseline,t1,t3 response but do not appear in medical history data
setdiff(baseline$ID, med_hist2$ID)
setdiff(t1$ID, med_hist2$ID)
setdiff(t3$ID, med_hist2$ID)

#remove these from questionaire data
baseline <- baseline[-which(baseline$ID==69 | baseline$ID==149),]
t1 <- t1[-which(t1$ID==69 | t1$ID==83 | t1$ID==100),]

#check that all baseline,t1,t3 responders are in medical data
setdiff(baseline$ID, med_hist2$ID)
setdiff(t1$ID, med_hist2$ID)
setdiff(t3$ID, med_hist2$ID)

#removing patients (IDs) from medical history data that do not appear in the final questionaire data

med_hist3 <- med_hist2[which(med_hist2$ID %in% baseline$ID),]
all.equal(med_hist3$ID,baseline$ID)

#Removing patients with radiation type=4 or 5
which(med_hist3$radiation_type==4 | med_hist3$radiation_type==5)
med_hist4 <- med_hist3[-which(med_hist3$radiation_type==4 | med_hist3$radiation_type==5),]

med_hist3$ID[which(med_hist3$radiation_type==4 | med_hist3$radiation_type==5)]
baseline <- baseline[-which(baseline$ID %in% med_hist3$ID[which(med_hist3$radiation_type==4 | med_hist3$radiation_type==5)]),]
t1 <- t1[-which(t1$ID %in% med_hist3$ID[which(med_hist3$radiation_type==4 | med_hist3$radiation_type==5)])]

#fixing the variable classes
med_hist4$Gender <- ifelse(med_hist4$Gender==1,0,1)
med_hist4$Gender <- factor(med_hist4$Gender)

med_hist4$Age_Group <- ifelse(med_hist4$Age_Group==1,0,1)
med_hist4$Age_Group <- factor(med_hist4$Age_Group)

med_hist4$prior_brain_radiation <- ifelse(grepl("o",med_hist4$prior_brain_radiation),0,1)
med_hist4$prior_brain_radiation <- factor(med_hist4$prior_brain_radiation)

table(med_hist4$radiation_type)
med_hist4$radiation_type <- factor(med_hist4$radiation_type)

med_hist4$prior_resection <- ifelse(grepl("o",med_hist4$prior_resection),0,1)
med_hist4$prior_resection <- factor(med_hist4$prior_resection)

med_hist4$histology <- ifelse(med_hist4$histology==5,0,1)
med_hist4$histology <- factor(med_hist4$histology)

med_hist4$concurrent_chemo <- ifelse(grepl("o",med_hist4$concurrent_chemo),0,1)
med_hist4$concurrent_chemo <- factor(med_hist4$concurrent_chemo)

med_hist4$cancer_still_affecting <- ifelse(grepl("o",med_hist4$cancer_still_affecting),0,1)
med_hist4$cancer_still_affecting <- factor(med_hist4$cancer_still_affecting)

#dropping tumor_histology and tumor_location because there are too many subgroups
names(med_hist4)
med_hist4 <- med_hist4[,-c(8,12)]

str(med_hist4)

#Adding medical history to each subset of the questionaire data

base_med <- merge(baseline,med_hist4)
t1_med <- merge(t1,med_hist4)
t3_med <- merge(t3,med_hist4)

#seeing if any of the data have missing values
which(rowSums(is.na(base_med))!=0)
which(rowSums(is.na(t1_med))!=0)
which(rowSums(is.na(t3_med))!=0)

#remove missing values from base_med data
base_med <- base_med[-which(rowSums(is.na(base_med))!=0),]

```

```{r include=FALSE}

#Consider all patients that had measurments at baseline, t1, and t3 (completed the study)
intersect(intersect(base_med$ID,t1_med$ID),t3_med$ID)
ids <- intersect(intersect(base_med$ID,t1_med$ID),t3_med$ID)
which(base_med$ID %in% ids)

completed <- base_med[which(base_med$ID %in% ids),]
dim(completed)

#consider all patients that had measurements at baseline and t1 (dropped out after t=1)
setdiff(intersect(base_med$ID,t1_med$ID),t3_med$ID)
ids <- setdiff(intersect(base_med$ID,t1_med$ID),t3_med$ID)
which(base_med$ID %in% ids)

dropout_after_1m <- base_med[which(base_med$ID %in% ids),]
dim(dropout_after_1m)

#consider all patients that only had measurement at baseline (dropped out after t=0)
setdiff(setdiff(base_med$ID,t1$ID),t3_med$ID)
ids <- setdiff(setdiff(base_med$ID,t1$ID),t3_med$ID)
which(base_med$ID %in% ids)

dropout_after_base <- base_med[which(base_med$ID %in% ids),]
dim(dropout_after_base)

```


```{r echo=FALSE}

out <- 
  structure(c(dim(completed)[1], dim(dropout_after_1m)[1], dim(dropout_after_base)[1],
              length(completed$Age_Group[which(completed$Age_Group==0)]), length(dropout_after_1m$Age_Group[which(dropout_after_1m$Age_Group==0)]), length(dropout_after_base$Age_Group[which(dropout_after_base$Age_Group==0)]),
              length(completed$Age_Group[which(completed$Age_Group==1)]), length(dropout_after_1m$Age_Group[which(dropout_after_1m$Age_Group==1)]), length(dropout_after_base$Age_Group[which(dropout_after_base$Age_Group==1)]),
              length(completed$Gender[which(completed$Gender==0)]), length(dropout_after_1m$Gender[which(dropout_after_1m$Gender==0)]), length(dropout_after_base$Gender[which(dropout_after_base$Gender==0)]),
              length(completed$Gender[which(completed$Gender==1)]), length(dropout_after_1m$Gender[which(dropout_after_1m$Gender==1)]), length(dropout_after_base$Gender[which(dropout_after_base$Gender==1)]),
              length(completed$prior_brain_radiation[which(completed$prior_brain_radiation==0)]), length(dropout_after_1m$prior_brain_radiation[which(dropout_after_1m$prior_brain_radiation==0)]), length(dropout_after_base$prior_brain_radiation[which(dropout_after_base$prior_brain_radiation==0)]),
              length(completed$prior_brain_radiation[which(completed$prior_brain_radiation==1)]), length(dropout_after_1m$prior_brain_radiation[which(dropout_after_1m$prior_brain_radiation==1)]), length(dropout_after_base$prior_brain_radiation[which(dropout_after_base$prior_brain_radiation==1)]),
              length(completed$prior_resection[which(completed$prior_resection==0)]), length(dropout_after_1m$prior_resection[which(dropout_after_1m$prior_resection==0)]), length(dropout_after_base$prior_resection[which(dropout_after_base$prior_resection==0)]),
              length(completed$prior_resection[which(completed$prior_resection==1)]), length(dropout_after_1m$prior_resection[which(dropout_after_1m$prior_resection==1)]), length(dropout_after_base$prior_resection[which(dropout_after_base$prior_resection==1)]),
              length(completed$cancer_still_affecting[which(completed$cancer_still_affecting==0)]), length(dropout_after_1m$cancer_still_affecting[which(dropout_after_1m$cancer_still_affecting==0)]), length(dropout_after_base$cancer_still_affecting[which(dropout_after_base$cancer_still_affecting==0)]),
              length(completed$cancer_still_affecting[which(completed$cancer_still_affecting==1)]), length(dropout_after_1m$cancer_still_affecting[which(dropout_after_1m$cancer_still_affecting==1)]), length(dropout_after_base$cancer_still_affecting[which(dropout_after_base$cancer_still_affecting==1)]),
              round(mean(completed$KPS),2), round(mean(dropout_after_1m$KPS),2), round(mean(dropout_after_base$KPS),2)
  ),
  .Dim = c(3L, 12L),
  .Dimnames = list(NULL, c("n", "al", "ag", "gm", "gn", "prn", "pry", "pren", "prey", "csn", "csy","kps")))

## format rows/cols
colnames(out) <- c("Total (n)", "Less than<br />60", "Greater than<br />or equal<br />to 60","M","F","No","Yes","No","Yes","No","Yes","Mean KPS")

rownames(out) <- c("Completed", "After 1 month", "After baseline")

## bolding rownames
rownames(out) <- sprintf('<b>%s</b>', rownames(out))

## table column headers (with line breaks (<br />))
cgroup <- c("", "Age", "Gender", "Prior Radiation<br />Treatment", "Prior Resection", "Cancer Still<br />Affecting","")

library(htmlTable)
htmlTable(out, rowlabel = "Time of<br />Dropout", 
          ctable = TRUE, align = 'cccccccccccc',
          ## number of columns that each cgroup label spans:
          n.cgroup = c(1,2,2,2,2,2,1), cgroup = cgroup,
          ## insert two table spanning sections:
          tspanner = c('',''),  # no labels
          n.tspanner = c(3), # number of rows to span (must sum to nrow(out))
#           css.tspanner.sep = "border-bottom: 1px dotted grey;",
          caption = "Number of patients remaining in the study at each interval separated by certain clinical and demographic strata.")#, 
          #tfoot = '<font size=1><sup>&dagger;</sup>Some note.</font>')


```

