---
title: "Literature Review"
author: "Spiro Stilianoudakis"
date: "November 7, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1) Krumholz HM, Lin Z, Keenan PS, Chen J, Ross JS, Drye EE, Bernheim SM, Wang Y, Bradley EH, Han LF, Normand ST. Relationship Between Hospital Readmission and Mortality Rates for Patients Hospitalized With Acute Myocardial Infarction, Heart Failure, or Pneumonia. JAMA. 2013;309(6):587-593. doi:10.1001/jama.2013.333

The objective of this study was to determine the relationship between hospital risk-standardized mortality rates (RSMRs) and risk-standardized readmission rates (RSRRs) overall and within subgroups defined by hospital characteristics. The authors studied Medicare fee-for-service beneficiaries discharged with acute myocardial infarction, heart failure, or pneumonia between July 1, 2005, and June 30, 2008 (4506 hospitals for acute myocardial infarction, 4767 hospitals for heart failure, and 4811 hospitals for pneumonia). They quantified the correlation between hospital RSMRs and RSRRs using weighted linear correlation; evaluated correlations in groups defined by hospital characteristics; and determined the proportion of hospitals with better and worse performance on both measures. Risk-standardized mortality rates and readmission rates were not associated for patients admitted with an acute myocardial infarction or pneumonia and were only weakly associated, within a certain range, for patients admitted with heart failure.

# 2) Tung Y-C, Chou S-H, Liu K-L, et al. Worse Prognosis in Heart Failure Patients with 30-Day Readmission . Acta Cardiologica Sinica. 2016;32(6):698-707.

This paper focused specifically on patients with heart failure. The study aimed to evaluate the readmission rate, outcome, and predictors of HF readmission. The patients were grouped into the readmission and the non-readmission groups. Readmission was defined as any rehospitalization or emergency department visit longer than 24 hours. Patients' baseline characteristics were recorded in a standard case report form. The demographic data included age, sex, occupation, marital status, and educational background. The clinical variables included cardiovascular risk factors and comorbidities such as hypertension, diabetes, etc. Other data collected were daily input/output records, body weight (BW), etc. The chi-square test with Fisher's exact test was used to compare categorical variables between the two groups. Continuous variables were compared utilizing the student's t-test. Kaplan-Meier survival curves and the log-rank test were used to compare survival of the readmission vs. the non-readmission groups and the CV vs. the non-CV causes of readmissions. The in-hospital and 6-month mortality rates were 3.9% and 15.2%, respectively. In those patients surviving the index HF hospitalization, the 30-day and 6-month readmission rates were 10.9% and 27%, respectively. At the end of the 6-month follow-up, the readmission group had higher mortality than the non-readmission group (27.66% vs. 10.36%; p = 0.001). The survivors of the 30-day readmission had similar mortality rates at 6 months, regardless of the cause of readmission (cardiovascular vs. non-cardiovascular: 25% vs. 30.43%, p = 0.677). Among all the parameters, prescription of beta blockers independently reduced the risk of 30-day readmission (odds ratio 0.15; 95% confidence interval 0.02-0.99; p = 0.049). 


# 3) Dharmarajan K, Wang Y, Lin Z, Normand ST, Ross JS, Horwitz LI, Desai NR, Suter LG, Drye EE, Bernheim SM, Krumholz HM. Association of Changing Hospital Readmission Rates With Mortality Rates After Hospital Discharge. JAMA. 2017;318(3):270-278. doi:10.1001/jama.2017.8444

This paper focused on readmission rates for patients with heart failure (HF), acute myocardial infarction (AMI), and pneumonia. This was a retrospective study of Medicare fee-for-service
beneficiaries aged 65 years or older. Monthly trends in each hospital's 30-day risk-adjusted readmission rates and 30-day risk-adjusted mortality rates after discharge were examined for each condition.  To do so, patient-level logistic regression models for 30-day readmission and 30-day mortality after discharge were separately fit. Models were fit
with all 7 years of data (2008-2014) separately for HF, AMI, and
pneumonia. Coefficients for predictor variables from these patient-level regression models were used to calculate expected outcome rates, 30-day risk-adjusted readmission rates, and 30-day risk-adjustedmortality rates after discharge for each hospital in each month using indirect standardization, defined as the observed outcome rate divided by the expected outcome rate (O/E)multiplied by the total crude outcome rate.
The total crude outcome rate for each condition was based on the 7-year study period. Differences in the characteristics of patients hospitalized with HF, AMI, or pneumonia over different study years were described using analysis of variance for continuous variables and chi-squared test for categorical variables. For each hospital, weighted linear regression and repeated monthly measures of its 30-day risk-adjusted readmission rates and 30-day risk-adjusted mortality rates after discharge were used to separately calculate monthly trends in its
30-day risk-adjusted readmission rates and 30-day riskadjustedmortality
rates after discharge for HF, AMI, and pneumonia. Weighting was based on the hospital monthly volume for each condition. Among Medicare fee-for-service beneficiaries hospitalized for heart failure, acute myocardial infarction, or pneumonia, reductions in hospital 30-day
readmission rates were weakly but significantly correlated with reductions in hospital 30-day mortality rates after discharge. 


# 4) Tabak YP, Sun X, Nunez CM, Gupta V, Johannes RS. Predicting Readmission at Early Hospitalization Using Electronic Clinical Data: An Early Readmission Risk Score. Medical Care. 2017;55(3):267-275. doi:10.1097/MLR.0000000000000654.

The objective of this study was 2-fold. First, the authors sought to develop an early readmission risk score (RRS) for all hospitalized adult patients, using clinical data at the time of admission. Second, they expanded the early RRS model to include administrative data that are available after patients are discharged. A published Acute Laboratory Risk of Mortality Score was used as an aggregated measure of clinical severity at admission and the number of hospital discharges in the previous 90 days as a measure of disease progression. The outcome variable was all-cause readmission within 30 days from index hospital discharge. Each live index hospital discharge date served as the starting date for the 30-day readmission window. A patient could have multiple admissions during the study period. They then evaluated the administrative data-enhanced model by adding principal and secondary diagnoses and other variables. They examined the c-statistic change when additional variables were added to the model. 


# 5) Low LL, Lee KH, Hock Ong ME, et al. Predicting 30-Day Readmissions: Performance of the LACE Index Compared with a Regression Model among General Medicine Patients in Singapore. BioMed Research International. 2015;2015:169870. doi:10.1155/2015/169870.

The LACE index (length of stay, acuity of admission, Charlson comorbidity index, CCI, and number of emergency department visits in preceding 6 months) derived in Canada, is used to predict readmission risk. The authors compared the performance of the LACE index with a derived model in identifying 30-day readmissions from a population of general medicine patients in Singapore. Additional variables include patient demographics, comorbidities, clinical and laboratory variables during the index admission, and prior healthcare utilization in the preceding year. 5,862 patients were analysed and 572 patients (9.8%) were readmitted in the 30 days following discharge. Age, CCI, count of surgical procedures during index admission, white cell count, serum albumin, and number of emergency department visits in previous 6 months were significantly associated with 30-day readmission risk. The final logistic regression model had fair discriminative ability c-statistic of 0.650 while the LACE index achieved c-statistic of 0.628 in predicting 30-day readmissions.


# 6) Huynh QL, Negishi K, Blizzard L, Sanderson K, Venn AJ, Marwick TH. Predictive Score for 30-Day Readmission or Death in Heart Failure . JAMA Cardiol. 2016;1(3):362-364. doi:10.1001/jamacardio.2016.0220

The authors developed a score for likelihood of readmission or death from HF from a prospective Australia-wide study of 430 HF patients (median age 74 years), of which 275 patients (64%) were male, and validated it in a group of 161 HF patients (median age 78 years), of which 89 patients (55%) were male. The primary outcome measure in the study was 30-day all-cause readmission or death. Data on readmission and death were collected from medical records. Clinical data included patient history, medications, physical measurements, blood tests, and findings on echocardiography. Nonclinical data included age, sex, language background, marital status, living alone or with others, education, socioeconomic status, remoteness index (differentiating residence in a metropolitan, rural, or remote area of Australia), medical insurance, and any home health care services provided. Questionnaires used for data collection included the Montreal Cognitive Assessment (MoCA), Patient Health Questionnaire (PHQ-9), and Generalized Anxiety Disorder (GAD-7). Logistic regression was used to determine the variables that served as the best predictors of readmission or death. Predictors were ranked by the change of deviance (G, the difference between null and residual deviance) that reflected the improvement in predictability provided by the univariable model as compared with the null model for each predictor.3 A predictor was included in the multivariable model if it contributed by 0.01 or more units to the area under the curve.4 Changes in standard errors when new variables were added were small (<10%), implying limited variance inflation in our models and no overfitting. The final model was internally validated through the use of 500 bootstrapped samples3 and externally validated by applying the intercept and regression coefficients to a cohort of 161 HF patients from Tasmania, Australia.


# 7) The day of the week and acute heart failure admissions: Relationship with acute myocardial infarction, 30-day readmission rate and in-hospital mortality

This study sought to assess this association between in-hospital mortality and weekend admission for HF using the Nationwide Inpatient Sample (NIS), while adjusting for relevant patient and hospital characteristics. This study also examined the role of weekend versus weekday discharge in affecting 30-day readmissions for acute heart failure among patients initially admitted with HF. Within the same population, the authors performed an analysis evaluating the relationship between hospital discharge on different days of the week and 30-day readmission. Friday was associated with the highest discharge and 30-day HF-readmission rate. Weekend HF admissions experienced more AMI, had greater comorbidities, received less cardiac procedures and predicted higher in-hospital mortality. Higher weekend mortality may be related to the greater degree of severity of illness among admitted patients.